Repository Kuama-IT/kuama_dart, pull requests merged in 2022-07, with the labels that each got.

#28 Feat update dependencies
  kuama_core/pubspec.yaml
  kuama_permissions/example/pubspec.yaml
  kuama_permissions/pubspec.yaml
  kuama_position/pubspec.yaml
Labels: enhancement, size/M

#29 Fix (PermissionsService) refresh permission on state resume
  kuama_permissions/example/pubspec.yaml
  kuama_permissions/lib/src/services/permissions_service.dart
Labels: enhancement, size/XS

#31 feat (Permissions) not request permission if it is already requested
  CHANGELOG.md
  kuama_core/pubspec.yaml
  kuama_permissions/example/pubspec.yaml
  kuama_permissions/lib/src/blocs/_permissions_event.dart
  kuama_permissions/lib/src/blocs/_permissions_state.dart
  kuama_permissions/lib/src/blocs/permissions_bloc.b.dart
  kuama_permissions/lib/src/blocs/permissions_bloc.b.g.dart
  kuama_permissions/lib/src/entities/permissions_status_entity.b.dart
  kuama_permissions/lib/src/entities/permissions_status_entity.b.g.dart
  kuama_permissions/lib/src/repositories/permissions_preferences_repository.dart
  kuama_permissions/lib/src/services/permissions_service.dart
  kuama_permissions/pubspec.yaml
  kuama_permissions/test/blocs/permissions_bloc_test.dart
  kuama_permissions/test/blocs/permissions_state_test.dart
  kuama_permissions/test/services/permissions_service_test.dart
  kuama_position/pubspec.yaml
Labels: enhancement, size/L

#32 fix (Permissions) refresh when app request permissions
  CHANGELOG.md
  kuama_core/pubspec.yaml
  kuama_permissions/lib/src/services/permissions_service.dart
  kuama_permissions/pubspec.yaml
  kuama_position/pubspec.yaml
Labels: bug, size/S
